### ISSUE TITLE
TypeError: e.includes is not a function

### ISSUE THREAD

**Issue by f-elix** [roxiness/routify#180]
Routify version: 1.7.8
Svelte version: 3.22.2

When I run the build script, either locally or with Netlify (note that I'm not using the deploy scripts provided by the starter template, I simply run build and point to the dist folder), the site gets "successfully" built, but I get a series of errors thrown and I just can't figure out what I'm doing wrong. 

Here is the relevant part of the log from the Netlify build (which is essentially the same as the local build log):

```
5:51:30 PM: TypeError: e.includes is not a function
5:51:30 PM:     at find.t (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24141)
5:51:30 PM:     at Array.find (<anonymous>)
5:51:30 PM:     at Object.console.warn (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24131)
5:51:30 PM:     at Hi (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:59890)
5:51:30 PM:     at getSessionsRange (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:79276)
5:51:30 PM:     at t.exec (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:46639)
5:51:30 PM:     at t.execute (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39544)
5:51:30 PM:     at t.update (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39788)
5:51:30 PM:     at eval (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:38259)
5:51:30 PM:     at t.process (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:36379)
5:51:30 PM: TypeError: e.includes is not a function
5:51:30 PM:     at find.t (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24141)
5:51:30 PM:     at Array.find (<anonymous>)
5:51:30 PM:     at Object.console.warn (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24131)
5:51:30 PM:     at Hi (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:59890)
5:51:30 PM:     at getAllExercises (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:90672)
5:51:30 PM:     at t.exec (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:46639)
5:51:30 PM:     at t.execute (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39544)
5:51:30 PM:     at t.update (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39788)
5:51:30 PM:     at eval (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:38259)
5:51:30 PM:     at t.process (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:36379)
5:51:30 PM: TypeError: e.includes is not a function
5:51:30 PM:     at find.t (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24141)
5:51:30 PM:     at Array.find (<anonymous>)
5:51:30 PM:     at Object.console.warn (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24131)
5:51:30 PM:     at Hi (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:59890)
5:51:30 PM:     at getTemplates (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:148178)
5:51:30 PM:     at t.exec (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:46639)
5:51:30 PM:     at t.execute (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39544)
5:51:30 PM:     at t.update (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39788)
5:51:30 PM:     at eval (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:38259)
5:51:30 PM:     at t.process (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:36379)
5:51:30 PM: TypeError: e.includes is not a function
5:51:30 PM:     at find.t (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24141)
5:51:30 PM:     at Array.find (<anonymous>)
5:51:30 PM:     at Object.console.warn (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24131)
5:51:30 PM:     at Hi (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:59890)
5:51:30 PM:     at getTemplates (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:148178)
5:51:30 PM:     at t.exec (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:46639)
5:51:30 PM:     at t.execute (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39544)
5:51:30 PM:     at t.update (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39788)
5:51:30 PM:     at eval (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:38259)
5:51:30 PM:     at t.process (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:36379)
5:51:31 PM: TypeError: e.includes is not a function
5:51:31 PM:     at find.t (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24141)
5:51:31 PM:     at Array.find (<anonymous>)
5:51:31 PM:     at Object.console.warn (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24131)
5:51:31 PM:     at Hi (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:59890)
5:51:31 PM:     at getAllExercises (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:90672)
5:51:31 PM:     at t.exec (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:46639)
5:51:31 PM:     at t.execute (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39544)
5:51:31 PM:     at t.update (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39788)
5:51:31 PM:     at eval (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:38259)
5:51:31 PM:     at t.process (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:36379)
5:51:31 PM: TypeError: e.includes is not a function
5:51:31 PM:     at find.t (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24141)
5:51:31 PM:     at Array.find (<anonymous>)
5:51:31 PM:     at Object.console.warn (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:1:24131)
5:51:31 PM:     at Hi (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:59890)
5:51:31 PM:     at getTemplates (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:148178)
5:51:31 PM:     at t.exec (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:46639)
5:51:31 PM:     at t.execute (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39544)
5:51:31 PM:     at t.update (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:39788)
5:51:31 PM:     at eval (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:38259)
5:51:31 PM:     at t.process (eval at Promise (/opt/build/repo/client/node_modules/@sveltech/ssr/ssr.js:64:24), <anonymous>:15:36379)
```

The 6th line of every block of error (between 'at Hi' and 't.exec') all refer to functions (like getAllExercises, getTemplates, etc.) that I define in separate js files and import into Svelte components.

Any idea what might be causing this? 

By the way, I really liked the DX with Routify, especially compared to Sapper, so I really hope to be able to use it for this app. This is a great project!

**Comment by jakobrosenberg** [comment]
Hi @f-elix 

Could you try run ``npm run dev`` and check a buggy page on port 5005? This might output a little more info in the console.

**Comment by f-elix** [comment]
Just tried it, I see nothing output in the console, either on real pages or buggy ones. What were you looking for?

**Comment by f-elix** [comment]
Ok I think I figured it out! I have some components that run these functions in the onMount hook. From what I understand, when the ssr function evaluates (eval) the bundle, it calls the onMount hooks. In each of these functions I use localStorage, which of course doesn't exist at build time, so it throws some errors. 

In the end, everything compiles just fine and the app runs, I just don't like seeing all these errors in the logs. 

I'm going to close this, as the onMount call during build has been discussed elsewhere.
