### ISSUE TITLE
Can't deploy to netllify

### ISSUE THREAD

**Issue by zerbusdetroy** [roxiness/routify#286]
**bug description**
Hello. Very pleased to discover this repo but after a very quick test I can't deploy to Netlify with the starter template.

Reproduction steps :

- `npx @roxi/routify init`
- push to a remote repository
- Configure Netlify as described [here](https://routify.dev/guide/starter-Template/deployment)
- Build on Netlify

Result:
`Error: ENOENT: no such file or directory, open 'public/build/bundle.js'`

**full trace**
```
1:21:17 AM: Starting build script
1:21:17 AM: Installing dependencies
1:21:17 AM: Python version set to 2.7
1:21:18 AM: v12.18.0 is already installed.
1:21:19 AM: Now using node v12.18.0 (npm v6.14.4)
1:21:19 AM: Started restoring cached build plugins
1:21:19 AM: Finished restoring cached build plugins
1:21:19 AM: Attempting ruby version 2.7.1, read from environment
1:21:20 AM: Using ruby version 2.7.1
1:21:21 AM: Using PHP version 5.6
1:21:21 AM: Started restoring cached node modules
1:21:21 AM: Finished restoring cached node modules
1:21:21 AM: Installing NPM modules using NPM version 6.14.4
1:21:22 AM: npm notice created a lockfile as package-lock.json. You should commit this file.
1:21:22 AM: npm WARN netlify No description
1:21:22 AM: npm WARN netlify No repository field.
1:21:22 AM: npm WARN netlify No license field.
1:21:22 AM: added 4 packages from 2 contributors and audited 4 packages in 0.653s
1:21:22 AM: found 0 vulnerabilities
1:21:22 AM: NPM modules installed
1:21:23 AM: Started restoring cached go cache
1:21:23 AM: Finished restoring cached go cache
1:21:23 AM: go version go1.14.4 linux/amd64
1:21:23 AM: go version go1.14.4 linux/amd64
1:21:23 AM: Installing missing commands
1:21:23 AM: Verify run directory
1:21:24 AM: ​
1:21:24 AM: ┌─────────────────────────────┐
1:21:24 AM: │        Netlify Build        │
1:21:24 AM: └─────────────────────────────┘
1:21:24 AM: ​
1:21:24 AM: ❯ Version
1:21:24 AM:   @netlify/build 5.2.1
1:21:24 AM: ​
1:21:24 AM: ❯ Flags
1:21:24 AM:   deployId: 5fb1c5f898ff030007f35669
1:21:24 AM:   mode: buildbot
1:21:24 AM: ​
1:21:24 AM: ❯ Current directory
1:21:24 AM:   /opt/build/repo/scripts/netlify
1:21:24 AM: ​
1:21:24 AM: ❯ Config file
1:21:24 AM:   /opt/build/repo/scripts/netlify/netlify.toml
1:21:24 AM: ​
1:21:24 AM: ❯ Context
1:21:24 AM:   production
1:21:25 AM: ​
1:21:25 AM: ┌───────────────────────────────────┐
1:21:25 AM: │ 1. Build command from Netlify app │
1:21:25 AM: └───────────────────────────────────┘
1:21:25 AM: ​
1:21:25 AM: $ npm run build
1:21:25 AM: > @ build /opt/build/repo/scripts/netlify
1:21:25 AM: > npm run build:app && npm run build:netlify
1:21:25 AM: > @ build:app /opt/build/repo/scripts/netlify
1:21:25 AM: > cd ../.. && npm i && npm run build
1:21:37 AM: > bufferutil@4.0.2 install /opt/build/repo/node_modules/bufferutil
1:21:37 AM: > node-gyp-build
1:21:37 AM: > utf-8-validate@5.0.3 install /opt/build/repo/node_modules/utf-8-validate
1:21:37 AM: > node-gyp-build
1:21:37 AM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/core-js
1:21:37 AM: > node -e "try{require('./postinstall')}catch(e){}"
1:21:37 AM: > ejs@2.7.4 postinstall /opt/build/repo/node_modules/ejs
1:21:37 AM: > node ./postinstall.js
1:21:37 AM: > esbuild@0.7.22 postinstall /opt/build/repo/node_modules/esbuild
1:21:37 AM: > node install.js
1:21:39 AM: > svelte-preprocess@4.5.2 postinstall /opt/build/repo/node_modules/svelte-preprocess
1:21:39 AM: > echo "[svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc..."
1:21:39 AM: [svelte-preprocess] Don't forget to install the preprocessors packages that will be used: node-sass/sass, stylus, less, postcss & postcss-load-config, coffeescript, pug, etc...
npm WARN svelte-app@1.0.0 No repository field.
1:21:39 AM: npm WARN svelte-app@1.0.0 No license field.
1:21:39 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
1:21:39 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1:21:39 AM: added 572 packages from 362 contributors and audited 575 packages in 13.429s
1:21:39 AM: 35 packages are looking for funding
1:21:39 AM:   run `npm fund` for details
1:21:39 AM: found 0 vulnerabilities
1:21:40 AM: > svelte-app@1.0.0 build /opt/build/repo
1:21:40 AM: > run-s build:*
1:21:40 AM: > svelte-app@1.0.0 build:app /opt/build/repo
1:21:40 AM: > routify -b && rollup -c
1:21:41 AM: [Routify] Generated routes in 1 ms
1:21:42 AM: 
1:21:42 AM: src/main.js → dist/build...
1:21:51 AM: The service worker file was written to dist/serviceworker.js
1:21:51 AM: The service worker will precache 3 URLs, totaling 5.07 kB.
1:21:53 AM: created dist/build in 10.3s
1:21:53 AM: > svelte-app@1.0.0 build:static /opt/build/repo
1:21:53 AM: > spank
1:21:54 AM: - Looking for matching config
1:21:54 AM: ✔ Found matching config: Routify 2
1:21:54 AM: - Looking for matching config
1:21:54 AM: ✔ Found matching config: Routify 2
1:21:56 AM: ✔ Inline dynamic imports
1:22:04 AM: ✔ Exported 80 pages in 7442 ms
1:22:04 AM: > @ build:netlify /opt/build/repo/scripts/netlify
1:22:04 AM: > node build && cd api/ssr && npm i
1:22:04 AM: internal/fs/utils.js:230
1:22:04 AM:     throw err;
1:22:04 AM:     ^
1:22:04 AM: Error: ENOENT: no such file or directory, open 'public/build/bundle.js'
1:22:04 AM:     at Object.openSync (fs.js:458:3)
1:22:04 AM:     at Object.readFileSync (fs.js:360:35)
1:22:04 AM:     at Object.<anonymous> (/opt/build/repo/scripts/netlify/build.js:14:16)
1:22:04 AM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
1:22:04 AM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
1:22:04 AM:     at Module.load (internal/modules/cjs/loader.js:986:32)
1:22:04 AM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
1:22:04 AM:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
1:22:04 AM:     at internal/main/run_main_module.js:17:47 {
1:22:04 AM:   errno: -2,
1:22:04 AM:   syscall: 'open',
1:22:04 AM:   code: 'ENOENT',
1:22:04 AM:   path: 'public/build/bundle.js'
1:22:04 AM: }
1:22:04 AM: npm ERR! code ELIFECYCLE
1:22:04 AM: npm ERR! errno 1
1:22:04 AM: npm ERR! @ build:netlify: `node build && cd api/ssr && npm i`
1:22:04 AM: npm ERR! Exit status 1
1:22:04 AM: npm ERR!
1:22:04 AM: npm ERR! Failed at the @ build:netlify script.
1:22:04 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1:22:04 AM: npm ERR! A complete log of this run can be found in:
1:22:04 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-16T00_22_04_954Z-debug.log
1:22:04 AM: npm ERR! code ELIFECYCLE
1:22:04 AM: npm ERR! errno 1
1:22:04 AM: npm ERR! @ build: `npm run build:app && npm run build:netlify`
1:22:04 AM: npm ERR! Exit status 1
1:22:04 AM: npm ERR!
1:22:04 AM: npm ERR! Failed at the @ build script.
1:22:04 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1:22:04 AM: npm ERR! A complete log of this run can be found in:
1:22:04 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-11-16T00_22_04_970Z-debug.log
1:22:04 AM: 
```

**Comment by jakobrosenberg** [comment]
Thanks for the heads up. This one slipped under the radar.

I'll have a fix ASAP.

**Comment by jakobrosenberg** [comment]
This is hopefully fixed now. If you can confirm, I'll update our documentation to reflect the new implementation.

To fix Netlify
1. copy the `api` folder from the updated starter template to your project. https://github.com/roxiness/routify-starter/tree/master/api
2. clear `base directory`, `build command` and `publish directory` in your Netlify `Build & Deploy` settings.

Example:
![image](https://user-images.githubusercontent.com/4153004/99252547-69d32d80-280f-11eb-805c-17ff4dcc629d.png)

**Comment by zerbusdetroy** [comment]
Perfect ! (updating netlify.toml too)

That was quick. Thank you

**Comment by jakobrosenberg** [comment]
I've updated the documentation. Assuming that this fixed your issue, I'm closing the issue for now. 🙂
