### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by sherjil** [roxiness/routify#287]
after running `npm run build `

```
(node:6615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_origin' of null
    at Window.get localStorage [as localStorage] (/Users/..../node_modules/jsdom/lib/jsdom/browser/Window.js:301:50)
    at a (eval at <anonymous> (/Users/...../tossr/tossr.js:68:24), <anonymous>:23:4384)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:6615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
⠋ Exporting 10 of 12 /soon/index/../index
```

Can anyone explain me what i am doing wrong here ...

**Comment by jakobrosenberg** [comment]
Got it solved? Looks like a case of `if (window.routify.inBrowser) ...`
