### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by ferulisses** [roxiness/routify#328]
Hi,

I'm getting this error when running npm run dev:
```
> Project@1.0.0 dev /home/fernando/Svelte/Project
> routify -c my-server

[Routify] Watching src/pages
[Routify] Generated routes in 0 ms

> Project@1.0.0 my-server /home/fernando/Svelte/Project
> rollup -c -w

[!] SyntaxError: Unexpected token 'export'
/home/fernando/Svelte/Project/node_modules/@roxi/routify/runtime/index.js:1
export { default as Router } from './Router.svelte'
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .js] (/home/fernando/Svelte/Project/node_modules/rollup/dist/shared/loadConfigFile.js:516:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fernando/Svelte/Project/rollup.config.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

I started with a basic Svelte App, incorporated TailwindCSS and made some development already, now I was about to install a route plugin and choose routify.

I followed the instructions on: 
https://routify.dev/guide/installation/install-to-existing-project

And in other blog posts and saw a pending bug opened, but I'm not sure what is wrong.

**package.json**
```
{
  "name": "Project",
  "version": "1.0.0",
  "scripts": {
    "dev": "routify -c my-server",
    "my-server": "rollup -c -w",
    "build": "routify -b && rollup -c",
    "start": "sirv public --single"
  },
  "routify": {
    "dynamicImports": false,
    "extensions": "svelte,html,svx,md"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.1.0",
    "@rollup/plugin-node-resolve": "^11.1.1",
    "@rollup/plugin-replace": "^2.3.4",
    "@rollup/plugin-strip": "^2.0.0",
    "@roxi/routify": "^2.8.5",
    "@tailwindcss/forms": "^0.2.1",
    "@tailwindcss/ui": "^0.7.2",
    "autoprefixer": "^10.2.4",
    "postcss": "^8.2.4",
    "postcss-load-config": "^3.0.0",
    "rollup": "^2.38.3",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.1.0",
    "rollup-plugin-terser": "^7.0.2",
    "svelte": "^3.32.1",
    "svelte-preprocess": "^4.6.5",
    "tailwindcss": "^2.0.2"
  },
  "dependencies": {
    "sirv-cli": "^1.0.11"
  }
}
```

**main.js**
```
import App from './App.svelte';

const app = new App({
	target: document.body,
});

export default app;
```

**rollup.config.js**
```
import svelte from "rollup-plugin-svelte";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import livereload from "rollup-plugin-livereload";
import { terser } from "rollup-plugin-terser";
import css from 'rollup-plugin-css-only';
import sveltePreprocess from "svelte-preprocess";
import replace from '@rollup/plugin-replace';
import strip from '@rollup/plugin-strip';
import {routify} from '@roxi/routify';

const production = !process.env.ROLLUP_WATCH;

const preprocess = sveltePreprocess({
  sourceMap: !production,
  postcss: {
    plugins: [
      require("tailwindcss"), 
      require("autoprefixer")
    ],
  },
});

function serve() {
  let server;

  function toExit() {
    if (server) server.kill(0);
  }

  return {
    writeBundle() {
      if (server) return;
      server = require("child_process").spawn(
        "npm",
        ["run", "start", "--", "--dev"],
        {
          stdio: ["ignore", "inherit", "inherit"],
          shell: true,
        }
      );

      process.on("SIGTERM", toExit);
      process.on("exit", toExit);
    },
  };
}

export default {
  input: "src/main.js",
  output: {
    sourcemap: true,
    // format: "iife",
    format: "esm",
    name: "app",
    // file: "public/build/bundle.js",
    dir: "public/build",
  },
  plugins: [
    svelte({
      // enable run-time checks when not in production
      // dev: !production,
      // we'll extract any component CSS out into
      // a separate file - better for performance
      // css: (css) => {
      //   css.write("bundle.css");
      // },
      preprocess,
    }),
    css({ output: 'bundle.css' }),

    routify({ dynamicImports : true}),

    // "Globals"
    replace({
      'MODE_ENV': JSON.stringify(production ? 'production' : 'development'),
      'SERVER_URL': JSON.stringify(production ? 'https://app.project.com' : 'http://localhost:3000'),
    }),
    
    strip({
      labels: ['unittest']
    }),

    // If you have external dependencies installed from
    // npm, you'll most likely need these plugins. In
    // some cases you'll need additional configuration -
    // consult the documentation for details:
    // https://github.com/rollup/plugins/tree/master/packages/commonjs
    resolve({
      browser: true,
      dedupe: ["svelte"],
    }),
    commonjs(),

    // In dev mode, call `npm run start` once
    // the bundle has been generated
    !production && serve(),

    // Watch the `public` directory and refresh the
    // browser on changes when not in production
    !production && livereload("public"),

    // If we're building for production (npm run build
    // instead of npm run dev), minify
    production && terser(),
  ],
  watch: {
    clearScreen: false,
  },
};
```

**App.svelte**
```
<script>
  import { Router } from "@roxi/routify";
  import { routes } from "../.routify/routes";

</script>
<style global=""></style>
<Router {routes} />
```

**Comment by ghostdevv** [comment]
@ferulisses You need to remove the routify import and function from rollup.config.js
