### ISSUE TITLE
Calling `$isActive` in library code throws error

### ISSUE THREAD

**Issue by nicolaiunrein** [roxiness/routify#338]
**bug description**
When calling `$isActive` inside an imported library. I get this error:
```
Failed to init component
<Test>
TypeError: Cannot read property 'params' of null
    at url (../auxcontrol-ui-toolkit/node_modules/@roxi/routify/runtime/helpers.js:213:61)
    at isActive (../auxcontrol-ui-toolkit/node_modules/@roxi/routify/runtime/helpers.js:333:16)
    at instance (eval at <anonymous> (http://localhost:5000/build/index.js:6599:17), <anonymous>:86:15)
    at init (node_modules/svelte/internal/index.mjs:1471:11)
    at new Test (eval at <anonymous> (http://localhost:5000/build/index.js:6599:17), <anonymous>:123:3)
    at createProxiedComponent (node_modules/svelte-hmr/runtime/svelte-hooks.js:206:9)
    at new ProxyComponent (node_modules/svelte-hmr/runtime/proxy.js:237:20)
    at new Proxy<Test> (node_modules/svelte-hmr/runtime/proxy.js:302:11)
    at create_fragment (eval at <anonymous> (http://localhost:5000/build/index.js:16:17), <anonymous>:42:9)
    at init (node_modules/svelte/internal/index.mjs:1486:37)
<Index>
TypeError: Cannot read property 'params' of null
    at url (../auxcontrol-ui-toolkit/node_modules/@roxi/routify/runtime/helpers.js:213:61)
    at isActive (../auxcontrol-ui-toolkit/node_modules/@roxi/routify/runtime/helpers.js:333:16)
    at instance (eval at <anonymous> (http://localhost:5000/build/index.js:6599:17), <anonymous>:86:15)
    at init (node_modules/svelte/internal/index.mjs:1471:11)
    at new Test (eval at <anonymous> (http://localhost:5000/build/index.js:6599:17), <anonymous>:123:3)
    at createProxiedComponent (node_modules/svelte-hmr/runtime/svelte-hooks.js:206:9)
    at new ProxyComponent (node_modules/svelte-hmr/runtime/proxy.js:237:20)
    at new Proxy<Test> (node_modules/svelte-hmr/runtime/proxy.js:302:11)
    at create_fragment (eval at <anonymous> (http://localhost:5000/build/index.js:16:17), <anonymous>:42:9)
    at init (node_modules/svelte/internal/index.mjs:1486:37)
<Noop>
TypeError: Cannot read property 'params' of null
    at url (../auxcontrol-ui-toolkit/node_modules/@roxi/routify/runtime/helpers.js:213:61)
    at isActive (../auxcontrol-ui-toolkit/node_modules/@roxi/routify/runtime/helpers.js:333:16)
    at instance (eval at <anonymous> (http://localhost:5000/build/index.js:6599:17), <anonymous>:86:15)
    at init (node_modules/svelte/internal/index.mjs:1471:11)
    at new Test (eval at <anonymous> (http://localhost:5000/build/index.js:6599:17), <anonymous>:123:3)
    at createProxiedComponent (node_modules/svelte-hmr/runtime/svelte-hooks.js:206:9)
    at new ProxyComponent (node_modules/svelte-hmr/runtime/proxy.js:237:20)
    at new Proxy<Test> (node_modules/svelte-hmr/runtime/proxy.js:302:11)
    at create_fragment (eval at <anonymous> (http://localhost:5000/build/index.js:16:17), <anonymous>:42:9)
    at init (node_modules/svelte/internal/index.mjs:1486:37)
```

**versions**
Routify:  2.12.5,
Svelte: 3.32.3

I checked the "routify" context inside my library and it is the same as in the consuming code.

If you need any more info or if I can help you in any way, feel free to ask. Would be nice to have this work!

**Comment by jakobrosenberg** [comment]
Can you provide a small step by step of what you're trying to do or a minimal reproducible project.

**Comment by nicolaiunrein** [comment]
I will create a minimal repo when I’m at the office

**Comment by nicolaiunrein** [comment]
I created a [minimal Repo](https://github.com/nicolaiunrein/routify-sample.git) with a library and a consumer project. Just follow the instructions in the README.md. Hope it helps!

**Comment by jakobrosenberg** [comment]
That was a beautiful repo!

**Comment by nicolaiunrein** [comment]
Hey, now I'm getting another error when running the sample repo. Tested both `v2.12.8` & `v2.12.9`. Did it work on your machine?
```
Uncaught TypeError: $currentRoute is null
    url ../../../../../node_modules/@roxi/routify/runtime/helpers.js:213
    isActive ../../../../../node_modules/@roxi/routify/runtime/helpers.js:333
    onClick http://localhost:5000/build/Error.js line 3381 > eval:84
    listen node_modules/svelte/internal/index.mjs:238
    listen_dev node_modules/svelte/internal/index.mjs:1616
    mount http://localhost:5000/build/Error.js line 3381 > eval:51
    m node_modules/svelte-hmr/runtime/svelte-hooks.js:158
    mount_component node_modules/svelte/internal/index.mjs:1412
    mount http://localhost:5000/build/Error.js line 16 > eval:47
    m node_modules/svelte-hmr/runtime/svelte-hooks.js:158
    mount_component node_modules/svelte/internal/index.mjs:1412
    mount http://localhost:5000/build/main.js line 2900 > eval:308
    mount http://localhost:5000/build/main.js line 3916 > eval:30
    m node_modules/svelte-hmr/runtime/svelte-hooks.js:158
    mount_component node_modules/svelte/internal/index.mjs:1412
    mount http://localhost:5000/build/main.js line 2900 > eval:413
    mount http://localhost:5000/build/main.js line 2900 > eval:81
    update http://localhost:5000/build/main.js line 2900 > eval:521
    update node_modules/svelte/internal/index.mjs:764
    flush node_modules/svelte/internal/index.mjs:732
    promise callback*schedule_update node_modules/svelte/internal/index.mjs:707
    make_dirty node_modules/svelte/internal/index.mjs:1444
    ctx node_modules/svelte/internal/index.mjs:1480
    onComponentLoaded http://localhost:5000/build/main.js line 2900 > eval:612
    promise callback*setComponent http://localhost:5000/build/main.js line 2900 > eval:607
    update http://localhost:5000/build/main.js line 2900 > eval:718
    init node_modules/svelte/internal/index.mjs:1485
    Route http://localhost:5000/build/main.js line 2900 > eval:743
    createProxiedComponent node_modules/svelte-hmr/runtime/svelte-hooks.js:206
    ProxyComponent node_modules/svelte-hmr/runtime/proxy.js:237
    Proxy<Route> node_modules/svelte-hmr/runtime/proxy.js:302
    create_if_block_1 http://localhost:5000/build/main.js line 2900 > eval:138
    create_default_slot_1 http://localhost:5000/build/main.js line 2900 > eval:199
    create_slot node_modules/svelte/internal/index.mjs:61
    create_fragment http://localhost:5000/build/_layout.js line 16 > eval:53
    init node_modules/svelte/internal/index.mjs:1489
    Layout http://localhost:5000/build/_layout.js line 16 > eval:185
    createProxiedComponent node_modules/svelte-hmr/runtime/svelte-hooks.js:206
    ProxyComponent node_modules/svelte-hmr/runtime/proxy.js:237
    Proxy<_layout> node_modules/svelte-hmr/runtime/proxy.js:302
    create_default_slot http://localhost:5000/build/main.js line 2900 > eval:298
    create_slot node_modules/svelte/internal/index.mjs:61
    create_fragment http://localhost:5000/build/main.js line 3916 > eval:19
    init node_modules/svelte/internal/index.mjs:1489
    Noop http://localhost:5000/build/main.js line 3916 > eval:99
    createProxiedComponent node_modules/svelte-hmr/runtime/svelte-hooks.js:206
    ProxyComponent node_modules/svelte-hmr/runtime/proxy.js:237
    Proxy<Noop> node_modules/svelte-hmr/runtime/proxy.js:302
    create_each_block http://localhost:5000/build/main.js line 2900 > eval:397
    create_if_block http://localhost:5000/build/main.js line 2900 > eval:68
    update http://localhost:5000/build/main.js line 2900 > eval:518
    update node_modules/svelte/internal/index.mjs:764
    flush node_modules/svelte/internal/index.mjs:732
    promise callback*schedule_update node_modules/svelte/internal/index.mjs:707
```

**Comment by ioannist** [comment]
we are running into the same error in 2.18.5

```
TypeError: Cannot read properties of undefined (reading 'params')
    at url (http://localhost:8080/build/bundle.js:873:61)
    at isActive (http://localhost:8080/build/bundle.js:993:16)
    at Array.checkActive (http://localhost:8080/build/bundle.js:10933:10)
    at Object.create [as c] (http://localhost:8080/build/bundle.js:10806:114)
    at create_component (http://localhost:8080/build/bundle.js:16600:20)
    at Object.create [as c] (http://localhost:8080/build/bundle.js:10194:69)
    at init (http://localhost:8080/build/bundle.js:16697:40)
    at new App (http://localhost:8080/build/bundle.js:10321:56)
    at createProxiedComponent (http://localhost:8080/build/bundle.js:8576:9)
    at new ProxyComponent (http://localhost:8080/build/bundle.js:8141:92)
```
